import {
    SubCommand,
    CommandRunner,
    Option,
    InquirerService,
} from 'nest-commander';
import { Injectable, NotFoundException } from '@nestjs/common';
import { UserService } from '../../../user/user.service';
import { PrismaService } from '@services/prisma.service';

/**
 * Options for creating a new system user
 */
interface CreateUserOptions {
    firstName?: string;
    lastName?: string;
    email?: string;
    role?: string;
    password?: string;
}

/**
 * Create User Subcommand
 *
 * Creates a new system user with the provided details.
 * If options are not provided via CLI flags, the user will be prompted
 * to enter them interactively using inquirer.
 *
 * Usage:
 *   bun run cli admin create-user [options]
 *
 * Options:
 *   -f, --first-name <firstName>  First name
 *   -l, --last-name <lastName>    Last name
 *   -e, --email <email>           Email address
 *   -r, --role <roleSlug>         Role slug (e.g., admin, user, moderator)
 *   -p, --password <password>     Password (optional - auto-generates if not provided)
 *
 * Examples:
 *   bun run cli admin create-user --first-name "John" --last-name "Doe" --email "john@example.com" --role "user"
 *   bun run cli admin create-user --first-name "Jane" --last-name "Doe" --email "jane@example.com" --role "user" --password "CustomPass123"
 *   bun run cli admin create-user  # Interactive mode
 */
@SubCommand({
    name: 'create-user',
    description: 'Create a new system user with a specific role',
})
@Injectable()
export class CreateUserCommand extends CommandRunner {
    constructor(
        private readonly inquirerService: InquirerService,
        private readonly userService: UserService,
        private readonly prisma: PrismaService,
    ) {
        super();
    }

    async run(inputs: string[], options: CreateUserOptions): Promise<void> {
        try {
            console.log('\n🔧 Creating a new system user...\n');

            // Prompt for missing options using inquirer
            const answers = await this.inquirerService.ask<CreateUserOptions>(
                'admin-create-user-questions',
                options,
            );

            // Merge CLI options with inquirer answers
            const finalOptions: CreateUserOptions = { ...options, ...answers };

            console.log(`🔍 Looking for role with slug: "${finalOptions.role}"`);

            // Verify the role exists by slug
            const role = await this.prisma.role.findFirst({
                where: { slug: finalOptions.role },
            });

            if (!role) {
                // Debug: List all available roles
                const allRoles = await this.prisma.role.findMany({
                    select: { id: true, name: true, slug: true, active: true },
                });
                console.log('\n📋 Available roles in database:');
                allRoles.forEach(r => {
                    console.log(`   - ${r.name} (slug: "${r.slug}", id: ${r.id}, active: ${r.active})`);
                });
                console.log('');

                throw new NotFoundException(
                    `Role with slug "${finalOptions.role}" not found. Please ensure the role exists in the system.`,
                );
            }

            console.log(`\n✓ Found role: ${role.name} (level: ${role.level})\n`);

            // Check if user already exists
            const existingUser = await this.userService.findOne({
                email: finalOptions.email!,
            });

            if (existingUser) {
                throw new Error(
                    `User with email "${finalOptions.email}" already exists (ID: ${existingUser.id})`,
                );
            }

            // Use provided password or generate a random one
            const password = finalOptions.password?.trim()
                ? finalOptions.password.trim()
                : Math.random().toString(36).slice(2) +
                Math.random().toString(36).slice(2);

            const isAutoGenerated = !finalOptions.password?.trim();

            // Create the user using UserService
            const createdUser = await this.userService.store({
                firstName: finalOptions.firstName!,
                lastName: finalOptions.lastName!,
                email: finalOptions.email!,
                password,
                roles: [finalOptions.role!],
                emailVerified: true, // System users are pre-verified
            });

            // Display success message
            this.displaySuccess(finalOptions, createdUser, password, role, isAutoGenerated);
        } catch (error) {
            this.displayError(error);
            process.exit(1);
        }
    }

    /**
     * Displays success message after user creation
     */
    private displaySuccess(
        userData: CreateUserOptions,
        createdUser: any,
        password: string,
        role: any,
        isAutoGenerated: boolean,
    ): void {
        const passwordNote = isAutoGenerated
            ? '(auto-generated)'
            : '(custom)';
        console.log(`
╔═══════════════════════════════════════════════════════════════╗
║            ✓ System User Created Successfully                 ║
╚═══════════════════════════════════════════════════════════════╝

User Details:
───────────────────────────────────────────────────────────────────
  ID:           ${createdUser?.id}
  First Name:   ${userData.firstName}
  Last Name:    ${userData.lastName}
  Full Name:    ${userData.firstName} ${userData.lastName}
  Email:        ${userData.email}
  Role:         ${role.name} (slug: ${role.slug}, level: ${role.level})
  Verified:     Yes
  Password:     ${password} ${passwordNote}
───────────────────────────────────────────────────────────────────

⚠️  IMPORTANT: Save the password above. It will not be shown again.
    The user should change this password on first login.
`);
    }

    /**
     * Displays error message
     */
    private displayError(error: unknown): void {
        const message = error instanceof Error ? error.message : 'Unknown error';
        console.error(`
╔═══════════════════════════════════════════════════════════════╗
║            ✗ Failed to Create System User                     ║
╚═══════════════════════════════════════════════════════════════╝

Error: ${message}
`);
    }

    @Option({
        flags: '-f, --first-name <firstName>',
        description: 'First name of the user',
    })
    parseFirstName(val: string): string {
        return val;
    }

    @Option({
        flags: '-l, --last-name <lastName>',
        description: 'Last name of the user',
    })
    parseLastName(val: string): string {
        return val;
    }

    @Option({
        flags: '-e, --email <email>',
        description: 'Email address of the user',
    })
    parseEmail(val: string): string {
        return val;
    }

    @Option({
        flags: '-r, --role <roleSlug>',
        description: 'Role slug to assign (e.g., admin, user, moderator)',
    })
    parseRole(val: string): string {
        return val;
    }

    @Option({
        flags: '-p, --password <password>',
        description: 'Password for the user (optional - auto-generates if not provided)',
    })
    parsePassword(val: string): string {
        return val;
    }
}
